### ISSUE TITLE
Add new goals

### ISSUE THREAD

**Issue by SpiderMath** [spantheslayer/spantheslayer#2]
Just noticed your GitHub profile. And looks like you still have your 2020 goals going on. Might wanna update it to 2022 ^_^

**Comment by spantheslayer** [comment]
haha yeah will do it. been busy with some other works :D 

Thank you for the notice:D

**Comment by SpiderMath** [comment]
Its January already 😅

**Comment by SpiderMath** [comment]
> haha yeah will do it
Nearly a year has passed :skull:
